branch-defaults:
  CIsetup:
    environment: null
    group_suffix: null
global:
  application_name: fondo-API
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 7.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
